complete hw2
Andrey582/NotificationBot pull request #2
Opened 2024-02-25 02:15 UTC by Andrey582

2024-03-03 16:27 UTC, lwbeamer requested changes

2024-03-03 16:27 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/commands/TrackCommand.java
> +        String link = msg[1];
Если укажу любой аргумент, то ссылка добавится, а нас интересуют только `GitHub` и `StackOverflow`. Нужно добавить проверку на валидность ссылки

2024-03-03 16:27 UTC, lwbeamer commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
> +@ComponentScan(basePackageClasses = GitHubController.class)
Кажется что это тут не нужно

2024-03-03 16:27 UTC, lwbeamer commented on scrapper/src/main/java/edu/java/dto/GitHubResponseDto.java
> +}
Какую информацию в итоге будет получать пользователь бота, подписавшийся на какой-нибудь репозиторий? Подозреваю что дата создания никак не меняется, поэтому нужно докинуть еще полей сюда по твоему усмотрению, хотя бы pushed_at, updated_at и т.д.

2024-03-03 16:27 UTC, lwbeamer commented on scrapper/src/main/resources/application.yml
> +  githubBaseUrl: https://api.github.com
В самих пропертях есть возможность указать env переменную, а через двоеточие дефолтное значение:

stackoverflowBaseUrl: ${STACKOVERFLOW_BASE_URL:[https://api.stackexchange.com/2.3/}](https://api.stackexchange.com/2.3/%7D)

Если переменная STACKOVERFLOW_BASE_URL задана при старте прилы - возьмется значение с нее, если нет - то дефолтное (после двоеточия)

Но это так, для справки, можно не править, у тебя тоже рабочий вариант

2024-03-03 16:34 UTC, lwbeamer commented on scrapper/src/main/java/edu/java/controller/GitHubController.java
> +    }
Пока контроллер не обязателен по заданию, поэтому менять в рамках этой дз не обязательно, но на будущее такой подход не очень хорош тем, что нет промежуточного сервисного уровня абстракции.
Контроллер-Сервис-Клиент/Репозиторий классическая трехвзенная архитектура, где более мене удобно масштабировать и добавлять новый функционал. У тебя же придется в случае чего менять код внутри контроллера, хотя он не несет ответственности за бизнес-логику, только за общение; 
Вообщем лучше вынести этот вызов в отдельный `GitHubIntegrationService`, и уже его внедрить сюда, в контроллер

2024-03-03 16:34 UTC, Andrey582 commented on scrapper/src/main/java/edu/java/dto/GitHubResponseDto.java
> +}
у меня запросы идут к эндпоинту event, так как на каждое изменение в репозитории создается свой ивент. Поэтому смотрю дату создания.

2024-03-08 22:34 UTC, lwbeamer commented on scrapper/src/main/java/edu/java/dto/GitHubResponseDto.java
> +}
Тогда норм, в будущих дз посмотрим, мб пригодится потом докинуть пару полей про событие, чтоб более детализированная инфа юзеру прилетала, но пока ок

2024-03-12 06:18 UTC, merged